# Netlify configuration file for Nuxt 3 SPA with Nuxt Kit
[build]
  # Build command for Nuxt 3 SPA
  command = "npx nuxi generate"
  # The directory where the generated static files are located
  publish = ".output/public"
  
  # Set the Node.js version to use during the build process
  environment = { NODE_VERSION = "20.9.0" }

# Redirect all traffic to index.html for SPA routing to work properly
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
