name = "nuxt-3-spa"
type = "javascript"
workers_dev = true
compatibility_date = "2024-09-16"

[build]
command = "npx nuxi generate"

[site]
bucket = ".output/public"

[build.environment]
NODE_VERSION = "20.9.0"

[env.production]
vars = { NODE_VERSION = "20.9.0" }

# Ensure all routes are directed to index.html for client-side routing
[[routes]]
pattern = "/**/*"
path = "/index.html"