name = "nuxt-3-spa"
compatibility_date = "2024-09-16"

[build]
command = "yarn install && yarn build"

[site]
bucket = ".output/public"

[build.environment]
NODE_VERSION = "20.9.0"

[env.production]
NODE_VERSION = "20.9.0"

# This is the key property that was missing
[build.output]
pages_build_output_dir = ".output/public"

# Ensure all routes are directed to index.html for client-side routing
[[routes]]
pattern = "/**/*"
path = "/index.html"